apiVersion: v3.0.2
kind: DataContract
id: bestandsdaten-kg-estg-v1.0.0
name: bestandsdaten_kg_estg_fakt
version: 1.0.0
status: test
domain: sozialleistungen
dataProduct: kindergeld-bestandsdaten
description:
  purpose: "Bereitstellung aggregierter Kindergeld-Bestandsdaten nach EStG f\xFCr\
    \  Controllingauswertungen."
  limitations: Daten sind anonymisiert und aggregiert. Keine personenbezogenen Daten.
schema:
- name: bestandsdaten_kg_estg_faktentabelle
  logicalType: object
  physicalType: table
  description: Faktentabelle mit Kindergeld-Bestandsdaten
  dataGranularityDescription: Ein Datensatz pro Monat, Gemeinde und Familienkasse.
  properties:
  - name: berichtsmonat
    primaryKey: true
    primaryKeyPosition: 1
    logicalType: date
    physicalType: date
    required: true
    description: dimension Berichtsmonat (Monatsende)
  - name: gemeindeschluessel
    primaryKey: true
    primaryKeyPosition: 2
    logicalType: string
    physicalType: varchar(8)
    required: true
    description: "Amtlicher Gemeindeschluessel (AGS)"
  - name: familienkasse
    primaryKey: true
    primaryKeyPosition: 3
    logicalType: string
    physicalType: varchar(50)
    required: true
    description: "Zustaendige Familienkasse"
  - name: anzahl_berechtigte
    logicalType: integer
    physicalType: bigint
    required: false
    description: Anzahl der Kunden mit Regelzahlung für den Berichtsmonat als Anspruchsmonat
  - name: anzahl_kinder
    logicalType: integer
    physicalType: bigint
    required: false
    description: Anzahl der Kinder mit Regelzahlung für den Berichtsmonat als Anspruchsmonat
  - name: summe_zahlungen
    logicalType: number
    physicalType: decimal(15,2)
    required: false
    description: Gesamtsumme der Kindergeld-Zahlungen in Euro
  quality:
  - name: eindeutige_primaerschluessel
    description: "Primaerschluessel-Kombination muss eindeutig sein"
    type: sql
    query: "SELECT COUNT(*) - COUNT(DISTINCT berichtsmonat, gemeindeschluessel, familienkasse)\
      \ \nFROM ${object}\n"
    mustBe: 0
    dimension: uniqueness
team:
- username: data.owner@arbeitsagentur.de
  role: Data Product Owner
  dateIn: '2024-01-01'
tenant: Famka
contractCreatedTs: '2025-08-04'
