apiVersion: v3.0.2
kind: DataContract
id: kindergeld-estg-v0.1.0
name: kindergeld-estg
version: 0.1.0
status: test
domain: sozialleistungen
dataProduct: kindergeld-bestandsdaten
description:
  purpose: "Bereitstellung aggregierter Kindergeld-Bestandsdaten nach EStG f\xFCr\
    \  Controllingauswertungen."
  limitations: Daten sind anonymisiert und aggregiert. Keine personenbezogenen Daten.

tags:
- Familienkasse
- Kindergeld

schema:
- name: kindergeld_estg
  logicalType: object
  physicalType: table
  description: Faktentabelle mit Kindergeld-Bestandsdaten
  dataGranularityDescription: Ein Datensatz pro Berichtsmonat, Gemeinde und Familienkasse.
  properties:
  - name: mon_id
    primaryKey: true
    primaryKeyPosition: 1
    logicalType: string
    description: >
      Monat der Berichterstattung. Entspricht dem Schlüssel in der Dimension
      'dim-berichtsmonat-v0.1.0'. Es sollen alle Standardeinstellungen der Dimension übernommen werden.
  - name: gem_id
    primaryKey: true
    primaryKeyPosition: 2
    logicalType: string
    description: >
      Gemeindeschlüssel. Entspricht dem Schlüssel in der Dimension
      'dim-gemeinde-v0.1.0'. Es sollen alle Standardeinstellungen der Dimension übernommen werden.
  - name: famka_id
    primaryKey: true
    primaryKeyPosition: 3
    logicalType: string
    description: >
      Familienkasse. Entspricht dem Schlüssel in der Dimension
      'dim-famka-v0.1.0'. Es sollen alle Standardeinstellungen der Dimension übernommen werden.
  - name: anzahl_berechtigte
    logicalType: integer
    physicalType: bigint
    required: false
    description: Anzahl der Kindergeld-Berechtigten
  - name: anzahl_kinder
    logicalType: integer
    physicalType: bigint
    required: false 
    description: Gesamtanzahl der Kinder
  quality:
  - name: eindeutige_primaerschluessel
    description: "Primaerschluessel-Kombination muss eindeutig sein"
    type: sql
    query: "SELECT COUNT(*) - COUNT(DISTINCT berichtsmonat, gemeindeschluessel, familienkasse)\
      \ \nFROM ${object}\n"
    mustBe: 0
    dimension: uniqueness

customProperties:
  - sourceTable: "tf_famka_knz_443"
  - imports:
    - id: dim-berichtsmonat-v0.1.0
    - id: dim-gemeinde-v0.1.0
    - id: dim-famka-v0.1.0
  - vendorExtensions:
    - ssas:
      - technicalPartition: mon_id

